/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
var certificado = {
    titular: 'JOSE ALBERTO BARBATO PORCASI',
    tipoDocumento: 'DNI',
    nroDocumento: '1234567',
    coordenadaX: '125.368',
    coordenadaY: '185.896',
    padronAntiguo: '777777777',
    padronVigente: '888888888',
    centroDistrito: 'XXXXXXXX',
    distritoROU: 'YYYYYYY',
    Vecinal: 'ZZZZZZZZ',
    nroParcelaProv: '458967',
    nroPartidaProv: '999999',
    nroManzana: '78',
    nroParcela: '88',
    nroSubparcela: '7',
    nroUnidad: '56',
    codCalleSinNomenclador: '10000001',
    codCalleOrdenanzaNueva: '10203040',
    nroPortal: '456789',
    nombreCalle: 'SARMIENTO',
    nroPlanoMensura: '777',
    nroLoteMensura: '23',
    nroOrdenanza: '15626/14',
    formaUnidad: 'IRREGULAR',
    medidaFrente: '20',
    medidaFondo: '25',
    medidaIzquierda: '50',
    medidaDerecha: '50',
    superficie: '250',
    afectaciones: '2',
    metros: '6',
    superficieAfectación: '15',
    anchoCalle: '25',
    anchoVereda: '20',
    distanciaEsquinas: '15/45',
    zonaInmobiliaria: 'ZONA OCHO',
    fechaVigencia: '12/03/2015',
    fechaAlta: '17/09/1985',
    fechaBaja: '03/06/2014',
    PH: 'NO',
    piso: '1',
    departamento: '104',
    uso: 'FAMILIAR',
    unidad: 'MULTIFAMILIAR',
    porcentajePH: '0',
    baldio: 'NO',
    codigoExpedición: 'CERT-CAT-2015-04-14',
    usuario: 'MFIGURA',
    fechaExpedicion: '15/04/2015',
    mapaImg: 'mapa.jpg'
};


